# Generated by Django 5.0.1 on 2024-02-10 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversation_id_alter_conversationmessage_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-modified_at']},
        ),
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ['-created_at']},
        ),
    ]
