# Generated by Django 5.0.1 on 2024-02-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ['created_at']},
        ),
    ]
