# Generated by Django 5.0.3 on 2024-03-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_alter_comment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
