# Generated by Django 5.0.1 on 2024-02-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='count',
            new_name='occurrence',
        ),
    ]
