# Generated by Django 5.0.1 on 2024-02-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0002_rename_count_hashtag_occurrence"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hashtag",
            options={"ordering": ["-occurrence"]},
        ),
    ]
