# Generated by Django 5.0.1 on 2024-02-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0003_alter_hashtag_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="hashtag",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
