# Generated by Django 5.0.1 on 2024-02-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_friends_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='friends_count',
            new_name='friend_count',
        ),
    ]
